#ifndef SNIGVRLPLUGIN_GLOBAL_H
#define SNIGVRLPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SNIGVRLPLUGIN_LIB
# define SNIGVRLPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define SNIGVRLPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // SNIGVRLPLUGIN_GLOBAL_H
