del /F /S *.bak
del  /F /S  *.ncb
del  /F /S  *.obj
del  /F /S  *.manifest
del  /F /S  *.pch
del  /F /S  *.pdb
del  /F /S  *.idb
del  /F /S  *.ilk
del  /F /S  *.exp
del  /F /S  *.htm
del  /F /S  *.dep
del  /F /S  *.user
del  /F /S  *.suo