#ifndef SNSILVERLINING_GLOBAL_H
#define SNSILVERLINING_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SNSILVERLINING_LIB
# define SNSILVERLINING_EXPORT Q_DECL_EXPORT
#else
# define SNSILVERLINING_EXPORT Q_DECL_IMPORT
#endif

#endif // SNSILVERLINING_GLOBAL_H
